### ISSUE TITLE
Rule Kalsel JS

### ISSUE THREAD

**Issue by muslih** [KalselJS/kalseljs#1]
Jadi rencana handak meulah rule kalsel-JS

### Target selesai 
Sekitar 22-31 Mei 2018
- [x] Telegram
- [x] Meetup/Event
- [x] Project

cc @muhammadridho

**Comment by muslih** [comment]
@muhammadridho rencana imak aturannya ini aturan kyp?

**Comment by muhammadridho** [comment]
kya tentang aturan di forum online (telegram) , sampai ke eventnya kang

**Comment by muslih** [comment]
@muhammadridho berarti sebarataan aturan lah?

**Comment by muhammadridho** [comment]
inggih, biar aman berataan

**Comment by muslih** [comment]
@muhammadridho kawa di list lah? 

1. Telegam
2. ....
3. ....

**Comment by muhammadridho** [comment]
1. Telgram
2. Meetup / Events
3. Project

**Comment by muhammadridho** [comment]
sdh tuntungkah mas ?

**Comment by muslih** [comment]
belum @muhammadridho mudahan weeken ini tuntung nah, amiiin

**Comment by muslih** [comment]
- [ ] Telegram
- [ ] Meetup/Event
- [ ] Project
