### ISSUE TITLE
Create Not Found Page

### ISSUE THREAD

**Issue by muhammadridho** [KalselJS/kalseljs#7]
![not found - mobile](https://user-images.githubusercontent.com/16620050/46256544-64eb7c80-c4d6-11e8-87cf-28de81b75bcc.png)
![not found page - desktop](https://user-images.githubusercontent.com/16620050/46256570-a54afa80-c4d6-11e8-8175-8f31e0896a15.png)

**Comment by muslih** [comment]
assetmya ada kah dho @muhammadridho ?

**Comment by muhammadridho** [comment]
hdang,
